apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager
  labels:
    app.kubernetes.io/name: gcp-secret-manager
    app.kubernetes.io/part-of: inenp-platform
spec:
  provider:
    gcpsm:
      projectID: dulcet-velocity-495612-j0
      auth:
        workloadIdentity:
          clusterLocation: europe-west3-a
          clusterName: inenp-dev-gke
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
