---
apiVersion: platform.inenp.at/v1alpha1
kind: TenantApplication
metadata:
  name: demo
  namespace: tenants
  labels:
    app.kubernetes.io/name: demo-tenant
    app.kubernetes.io/part-of: inenp-platform
    inenp.at/environment: demo
    inenp.at/tenant: demo
spec:
  parameters:
    tenantName: demo
    environment: demo
    hostname: demo.inenp.naehrer.me
    frontendImageTag: 2c3e96c3f4962723d823e6b09da0ef521f5cc0d9
    backendImageTag: f5feb13942519da31cfac8f87ebdd58fd0cc0784
    databaseSize: small
