apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  namespace: argocd
  labels:
    app.kubernetes.io/name: cloudnative-pg
    app.kubernetes.io/part-of: inenp-platform
spec:
  project: default
  source:
    repoURL: https://cloudnative-pg.github.io/charts
    chart: cloudnative-pg
    targetRevision: 0.23.2
    helm:
      releaseName: cloudnative-pg
      valuesObject:
        monitoring:
          podMonitorEnabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
