apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-secret-store
  namespace: argocd
  labels:
    app.kubernetes.io/name: cluster-secret-store
    app.kubernetes.io/part-of: inenp-platform
spec:
  project: default
  source:
    repoURL: https://github.com/FHB-MCCE/INENP-k8s-platform-gitops.git
    targetRevision: main
    path: infrastructure/external-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
